# Generated by Django 5.1.1 on 2025-03-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.PositiveIntegerField()),
                ('correo', models.CharField(max_length=254)),
                ('contraseña', models.CharField(max_length=254)),
                ('rol', models.IntegerField(choices=[(1, 'Admin'), (2, 'Usuario'), (3, 'Empleado')], default=2)),
            ],
        ),
    ]
