# Generated by Django 5.1.1 on 2025-03-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidandoHuellas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
