# Generated by Django 5.1.1 on 2025-03-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidandoHuellas', '0002_alter_usuario_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('foto_producto', models.ImageField(upload_to='foto_producto/')),
                ('categoria', models.IntegerField(choices=[(0, ''), (1, 'Alimentos Mascotas'), (2, 'Accesorios Mascotas'), (3, 'Ropa Mascotas')], default=0)),
                ('estado', models.IntegerField(choices=[(0, ''), (1, 'Disponible'), (2, 'No Disponible')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.PositiveIntegerField(),
        ),
    ]
