# Generated by Django 5.1.1 on 2025-04-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidandoHuellas', '0003_producto_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[(0, ''), (1, 'Alimentos Mascotas'), (2, 'Accesorios Mascotas'), (3, 'Ropa Mascotas')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[(0, ''), (1, 'Disponible'), (2, 'No Disponible')], default=0, max_length=20),
        ),
    ]
