# Generated by Django 5.1.1 on 2025-04-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidandoHuellas', '0004_alter_producto_categoria_alter_producto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(default=34, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
