# Generated by Django 5.1.1 on 2025-04-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidandoHuellas', '0010_publicacionmascota_fotomascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionmascota',
            name='tipo_publicacion',
            field=models.CharField(choices=[('perdida', 'Mascota Perdida'), ('adopcion', 'Mascota en Adopción')], default='perdida', max_length=10),
        ),
    ]
