# Generated by Django 5.1.1 on 2025-04-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidandoHuellas', '0011_publicacionmascota_tipo_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionmascota',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicacionmascota',
            name='edad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publicacionmascota',
            name='nombre_mascota',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicacionmascota',
            name='raza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicacionmascota',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
