# Generated by Django 5.1.1 on 2025-04-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidandoHuellas', '0012_publicacionmascota_contacto_publicacionmascota_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
