# Generated by Django 5.1.2 on 2025-04-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidandoHuellas', '0013_alter_usuario_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ultima_compra',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última compra'),
        ),
        migrations.AddField(
            model_name='producto',
            name='veces_comprado',
            field=models.PositiveIntegerField(default=0, verbose_name='Veces comprado'),
        ),
    ]
