# Generated by Django 5.1.2 on 2025-05-01 20:23

import cuidandoHuellas.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidandoHuellas', '0014_producto_ultima_compra_producto_veces_comprado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotomascota',
            name='imagen',
            field=models.ImageField(upload_to='fotos_mascotas/', validators=[cuidandoHuellas.validators.validar_extension_imagen]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='publicacionmascota',
            name='contacto',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El contacto debe contener entre 7 y 15 dígitos', regex='^\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='publicacionmascota',
            name='edad',
            field=models.PositiveIntegerField(blank=True, help_text='Edad en años', null=True),
        ),
        migrations.AlterField(
            model_name='publicacionmascota',
            name='nombre_mascota',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='publicacionmascota',
            name='raza',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='La raza solo puede contener letras y espacios', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='publicacionmascota',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='publicacionmascota',
            name='tipo_publicacion',
            field=models.CharField(choices=[('perdida', 'Mascota Perdida'), ('adopcion', 'Mascota en Adopción')], max_length=10),
        ),
    ]
