# Generated by Django 5.1.2 on 2025-05-10 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidandoHuellas', '0016_usuario_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('inapropiado', 'Contenido inapropiado'), ('estafa', 'Posible estafa'), ('spam', 'Spam'), ('otros', 'Otros')], max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='cuidandoHuellas.publicacionmascota')),
                ('usuario_reportero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_hechos', to='cuidandoHuellas.usuario')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
