# Generated by Django 5.1.1 on 2025-05-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidandoHuellas', '0017_reporte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='resuelto',
            new_name='revisado',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='perfiles/'),
        ),
    ]
