# Generated by Django 5.2 on 2025-05-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidandoHuellas', '0020_usuario_estado_usuario_motivo_inhabilitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('alimentos', 'Alimentos'), ('accesorios', 'Accesorios'), ('ropa', 'Ropa'), ('salud', 'Salud')], default=0, max_length=20),
        ),
    ]
