# Generated by Django 5.1.6 on 2025-07-05 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidandoHuellas', '0024_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='categoria',
            field=models.CharField(choices=[('Problema técnico', 'Problema técnico'), ('Consulta general', 'Consulta general'), ('Reporte de error', 'Reporte de error'), ('Sugerencia', 'Sugerencia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketsoporte',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='cuidandoHuellas.usuario'),
        ),
    ]
