# Generated by Django 5.1.6 on 2025-07-05 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidandoHuellas', '0025_alter_ticket_categoria_alter_ticketsoporte_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaticket',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuidandoHuellas.usuario'),
        ),
    ]
