# Generated by Django 5.1.6 on 2025-07-05 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuidandoHuellas', '0026_alter_respuestaticket_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketsoporte',
            old_name='usuario',
            new_name='usuusuario',
        ),
    ]
