# Generated by Django 5.1.6 on 2025-07-05 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuidandoHuellas', '0027_rename_usuario_ticketsoporte_usuusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketsoporte',
            old_name='usuusuario',
            new_name='usuario',
        ),
    ]
